# Generated by Django 5.0.1 on 2025-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('acara', models.CharField(max_length=200)),
            ],
        ),
    ]
