# Generated by Django 5.0.1 on 2025-09-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwal',
            old_name='acara',
            new_name='nama_acara',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='jam_mulai',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='jam_selesai',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='waktu',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
